//! Verify that every Orbiter-owned Rust function carries meaningful documentation.
//!
//! `missing_docs` only covers items reachable through a crate's public API, so it says nothing
//! about private helpers, trait implementations, nested functions or tests — which is most of this
//! codebase. Searching for `///` with a regular expression proves even less: `fn` occurs inside
//! string literals, comments and macro bodies, and doc comments can be attached to the wrong item.
//!
//! This walks the real syntax tree instead. It reports every function-like item that has no
//! documentation, and every module that does not describe itself, and exits non-zero when any
//! remain — so it can run in the same breath as `clippy` and `cargo fmt --check`.
//!
//! Run it from the repository root:
//!
//! ```text
//! cargo run --offline -p doc-audit
//! ```

use std::{path::Path, process::ExitCode};
use syn::{
    Attribute, ImplItem, Item, ItemFn, ItemMod, TraitItem,
    visit::{self, Visit},
};

/// Directories and files that are Orbiter's own Rust, in audit order.
///
/// Vendored dependencies under `vendor/` and build output under `target/` are deliberately absent:
/// the requirement is that *Orbiter's* code is documented, and holding third-party sources to it
/// would bury the signal.
const ROOTS: &[&str] = &[
    "crates/orbiter-core/src",
    "crates/orbiter-core/tests",
    "crates/orbiter-core/build.rs",
    "crates/doc-audit/src",
    "src-tauri/src",
];

/// One item that ought to describe itself and does not.
struct Gap {
    /// Repository-relative path, so the line can be pasted into an editor.
    file: String,
    line: usize,
    /// What kind of item it is, for the summary counts.
    kind: &'static str,
    /// The item's name, qualified by its `impl` block where that is what identifies it.
    name: String,
}

/// Whether any attribute is a doc comment (`///`, `//!`, or an explicit `#[doc = "…"]`).
///
/// Emptiness is not judged here: a doc comment that says nothing is a review problem, not
/// something a syntax tree can detect. What this catches is the absence of one.
fn documented(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| attr.path().is_ident("doc"))
}

/// Whether an item is generated by a macro expansion rather than written in this file.
///
/// `#[automatically_derived]` marks the impl blocks that `#[derive(...)]` produces. Their methods
/// are not Orbiter's to document, and requiring it would be asking for documentation on code that
/// does not exist in the source.
fn derived(attrs: &[Attribute]) -> bool {
    attrs
        .iter()
        .any(|attr| attr.path().is_ident("automatically_derived"))
}

/// Collects undocumented items from one parsed file.
struct Audit {
    /// Repository-relative path of the file being walked.
    file: String,
    /// The `impl` or `trait` currently being walked, used to qualify method names.
    scope: Vec<String>,
    /// Every gap found so far, in source order.
    gaps: Vec<Gap>,
}

impl Audit {
    /// Record one undocumented item, qualifying its name with the enclosing `impl` or `trait`.
    fn gap(&mut self, kind: &'static str, name: String, line: usize) {
        let name = match self.scope.last() {
            Some(scope) => format!("{scope}::{name}"),
            None => name,
        };
        self.gaps.push(Gap {
            file: self.file.clone(),
            line,
            kind,
            name,
        });
    }
}

impl<'ast> Visit<'ast> for Audit {
    /// Check a free function, including one nested inside another function's body.
    ///
    /// Nested functions are visited because `visit_item_fn` fires for `Item::Fn` wherever it
    /// appears, and a helper hidden inside a long workflow is exactly the kind of code a reader
    /// most needs explained.
    fn visit_item_fn(&mut self, node: &'ast ItemFn) {
        if !documented(&node.attrs) {
            self.gap(
                "fn",
                node.sig.ident.to_string(),
                node.sig.ident.span().start().line,
            );
        }
        visit::visit_item_fn(self, node);
    }

    /// Check every method of an inherent or trait implementation.
    ///
    /// Implementations that `#[derive]` produced are skipped; everything else, including `Drop`,
    /// `Default` and conversions, is held to the same requirement as any other function.
    fn visit_item_impl(&mut self, node: &'ast syn::ItemImpl) {
        if derived(&node.attrs) {
            return;
        }
        let name = match &*node.self_ty {
            syn::Type::Path(path) => path
                .path
                .segments
                .last()
                .map(|segment| segment.ident.to_string())
                .unwrap_or_else(|| "impl".to_owned()),
            _ => "impl".to_owned(),
        };
        self.scope.push(name);
        for item in &node.items {
            if let ImplItem::Fn(method) = item
                && !documented(&method.attrs)
            {
                let line = method.sig.ident.span().start().line;
                self.gap("method", method.sig.ident.to_string(), line);
            }
        }
        visit::visit_item_impl(self, node);
        self.scope.pop();
    }

    /// Check every method a trait declares, whether or not it has a default body.
    fn visit_item_trait(&mut self, node: &'ast syn::ItemTrait) {
        self.scope.push(node.ident.to_string());
        for item in &node.items {
            if let TraitItem::Fn(method) = item
                && !documented(&method.attrs)
            {
                let line = method.sig.ident.span().start().line;
                self.gap("trait method", method.sig.ident.to_string(), line);
            }
        }
        visit::visit_item_trait(self, node);
        self.scope.pop();
    }

    /// Check that a module describes itself, then walk its contents.
    ///
    /// An inline `mod tests { … }` counts: a reader arriving at a test module deserves to be told
    /// what area it covers before reading twenty assertions.
    fn visit_item_mod(&mut self, node: &'ast ItemMod) {
        // Only inline modules. A `mod foo;` declaration's documentation is the `//!` header of
        // `foo.rs`, which this tool checks when it walks that file — flagging the declaration too
        // would demand the same text in two places.
        if let Some((_, items)) = &node.content
            && !documented(&node.attrs)
            && !items.iter().any(has_inner_doc)
        {
            self.gap(
                "mod",
                node.ident.to_string(),
                node.ident.span().start().line,
            );
        }
        visit::visit_item_mod(self, node);
    }
}

/// Whether an item inside a module body is an inner doc comment (`//!`) for that module.
///
/// `syn` models `//!` at the top of an inline module as a `#[doc]` attribute on the module's own
/// items list rather than on the module, so a module documented that way would otherwise look
/// undocumented.
fn has_inner_doc(item: &Item) -> bool {
    matches!(item, Item::Verbatim(tokens) if tokens.to_string().starts_with("#!"))
}

/// Walk one file and return everything in it that lacks documentation.
///
/// # Errors
///
/// Returns the parse or read failure as a message. A file this tool cannot parse is reported
/// rather than skipped: silently passing a file it could not read would make the audit a lie.
fn audit_file(path: &Path, root: &Path) -> Result<Vec<Gap>, String> {
    let text =
        std::fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
    let parsed = syn::parse_file(&text).map_err(|error| format!("{}: {error}", path.display()))?;
    let file = path
        .strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .into_owned();
    let mut audit = Audit {
        file,
        scope: Vec::new(),
        gaps: Vec::new(),
    };
    // A file with no `//!` header does not describe itself. Crate roots and module files both
    // carry one in this codebase, and a new file without one is the gap worth catching early.
    if !parsed.attrs.iter().any(|attr| attr.path().is_ident("doc")) {
        audit.gap("file", audit.file.clone(), 1);
    }
    audit.visit_file(&parsed);
    Ok(audit.gaps)
}

/// Audit every Orbiter-owned Rust file and print what is missing.
///
/// # Errors
///
/// Exits with a failure code when any file cannot be parsed or any item lacks documentation, so
/// the audit can be wired into the same check run as `clippy` and `cargo fmt --check`.
fn main() -> ExitCode {
    let root = std::env::current_dir().unwrap_or_else(|_| Path::new(".").to_path_buf());
    let mut gaps = Vec::new();
    let mut failures = Vec::new();
    let mut files = 0usize;
    for entry in ROOTS {
        let start = root.join(entry);
        if !start.exists() {
            failures.push(format!("{entry}: not found"));
            continue;
        }
        for found in walkdir::WalkDir::new(&start).sort_by_file_name() {
            let found = match found {
                Ok(found) => found,
                Err(error) => {
                    failures.push(error.to_string());
                    continue;
                }
            };
            if !found.file_type().is_file() || found.path().extension().is_none_or(|e| e != "rs") {
                continue;
            }
            files += 1;
            match audit_file(found.path(), &root) {
                Ok(found) => gaps.extend(found),
                Err(error) => failures.push(error),
            }
        }
    }
    for failure in &failures {
        println!("could not audit {failure}");
    }
    for gap in &gaps {
        println!(
            "{}:{} undocumented {} `{}`",
            gap.file, gap.line, gap.kind, gap.name
        );
    }
    println!(
        "\n{files} file(s) audited, {} undocumented item(s)",
        gaps.len()
    );
    if gaps.is_empty() && failures.is_empty() {
        println!("every Orbiter-owned function, module and file is documented");
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}
